### ISSUE TITLE
[homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

### ISSUE THREAD

**Issue by RowdyMuncher** [jfarmer08/homebridge-wyze-smart-home#92] opened 2023-04-07 20:46 UTC
**Describe Your Problem:**
I have installed your plugin after setting up my wyze account username and password and 2fa the plugin starts but an error is shown. I am not sure why this is happening or how to fix it.

[08/04/2023, 06:36:24] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

**Logs:**

[08/04/2023, 06:37:08] Homebridge v2.0.0-beta.0 (HAP v1.0.0-beta.5) (Homebridge 0955) is running on port 51980.
[08/04/2023, 06:37:10] [Wyze] Launched child bridge with PID 6255
[08/04/2023, 06:37:11] Registering platform 'homebridge-wyze-smart-home.WyzeSmartHome'
[08/04/2023, 06:37:11] [Wyze] Loaded homebridge-wyze-smart-home v0.5.26 child bridge successfully
[08/04/2023, 06:37:11] Loaded 5 cached accessories from cachedAccessories.0EF4323DBD81.
[08/04/2023, 06:37:11] Homebridge v2.0.0-beta.0 (HAP v1.0.0-beta.5) (Wyze) is running on port 52743.
[08/04/2023, 06:37:11] [Ring] Found the following locations:
[08/04/2023, 06:37:11] [Ring]   locationId: r1r0m1-26624-0 - xxxxxxxxx
[08/04/2023, 06:37:12] [Ring] Configuring 1 cameras and 3 devices for location "Gold Coast home" - locationId: r1r0m1-26624-0
[08/04/2023, 06:37:12] [Ring] Configured camera ee295bc5-43ee-4ce9-b891-afcd6168a979 doorbell_scallop_lite Front Door
[08/04/2023, 06:37:12] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:37:12] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:37:12] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:37:13] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:37:13] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:37:13] Front Door 07F1 is running on port 37707.
[08/04/2023, 06:37:13] Please add [Front Door 07F1] manually in Home app. Setup Code: 898-08-123
[08/04/2023, 06:38:14] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:38:14] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:38:14] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:38:14] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:38:14] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:39:15] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:39:15] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:39:15] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:39:15] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[08/04/2023, 06:39:15] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

**Plugin Config:**

{
    "name": "Wyze",
    "username": "efraim@emailaddress.com.au",
    "password": "xxxxxxxx!",
    "refreshInterval": 60000,
    "entryExitDelay": 30,
    "mfaCode": "xxxxxx",
    "showAdvancedOptions": false,
    "excludeMacAddress": false,
    "excludedeviceType": false,
    "_bridge": {
        "username": "0E:F4:32:3D:BD:81",
        "port": 52743
    },
    "platform": "WyzeSmartHome"
}

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**:homebridge-config-ui-x v4.50.2
* **Node.js Version**: <not sure where to find>
* **NPM Version**: <Not sure where to find>
* **Operating System**: Raspbian GNU/Linux Bullseye (11)

**Comment by Nyxholas** [comment] 2023-04-08 01:51
Having this same exact issue.

**Comment by anderfrank** [comment] 2023-04-24 15:21
I have noticed that both of my Pan Cam v1 on/off switches from the plugin are always "off" even if the camera is turned on in the Wyze app. All other camera switches from the plugin are working properly. Maybe this is the cause of the warning message?

If I turn them on they stay on for a short time but then turn off again (camera is still on). If I turn them on and then off they will turn the camera off, so they seem to be working in some way but not fully as they should.

**Comment by anderfrank** [comment] 2023-04-27 14:28
> Noticing the same issue on 0.5.26 -- Pan Cam v3 on/off switch is always "off" even if camera is turned on. I also have a regular Wyze Cam v3 which does not have this issue with the switch. I have no in-wall switches.

See my last comment on an issue I created. You can fix this manually by editing a .js file. Alternatively there appears to be a pending pull request that has removed the filter on the cameras which will also fix the error.

https://github.com/jfarmer08/homebridge-wyze-smart-home/issues/87

**Comment by jfarmer08** [comment] 2023-06-29 19:14
I dont plan on removing this check, since not all Cams work the same way.

**Comment by anderfrank** [comment] 2023-06-30 00:57
Can more camera models like WYZECP1_JEF (Pan Cam v1) be added so they are usable by the plugin without having to manually edit the .js file?

**Comment by jfarmer08** [comment] 2023-06-30 01:44
Yes if they are confirmed working I will add them.

**Comment by anderfrank** [comment] 2023-06-30 13:17
At the very least I know WYZECP1_JEF works with this plugin.

**Comment by traviswparker** [comment] 2023-07-05 02:30
> Yes if they are confirmed working I will add them. 

I’m using docker-wyze-bridge for RTSP video. The list of cameras marked as supported at https://github.com/mrlt8/docker-wyze-bridge should give you an idea of the ones you should be able to control the power/privacy on, as wyze-bridge does power control as well.

I can personally confirm HL_PAN3 works if that model is added.

**Comment by iamvidoq** [comment] 2023-07-11 20:33
I get this error every minute now. Is there a fix?

[7/11/2023, 4:27:20 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[7/11/2023, 4:28:20 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[7/11/2023, 4:29:21 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[7/11/2023, 4:30:22 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[7/11/2023, 4:31:23 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.
[7/11/2023, 4:32:24 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

**Comment by anderfrank** [comment] 2023-07-11 21:17
> I get this error every minute now. Is there a fix?
> 
> [7/11/2023, 4:27:20 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info. [7/11/2023, 4:28:20 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info. [7/11/2023, 4:29:21 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info. [7/11/2023, 4:30:22 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info. [7/11/2023, 4:31:23 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info. [7/11/2023, 4:32:24 PM] [homebridge-wyze-smart-home] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://homebridge.io/w/JtMGR for more info.

What camera(s) do you have? It likely needs added to the WyzeAccessory.js file.

**Comment by iamvidoq** [comment] 2023-07-11 21:20
One Pan Cam v2 and five v2 cams.

**Comment by anderfrank** [comment] 2023-07-11 21:29
HL_PAN2 needs to be added to WyzeAccessory.js, lines 169/170

**Comment by iamvidoq** [comment] 2023-07-11 21:47
Sorry is there a simple way to find that file to edit?

**Comment by anderfrank** [comment] 2023-07-11 21:49
What do you have Homebridge installed on?

**Comment by iamvidoq** [comment] 2023-07-11 21:52
My imac

**Comment by anderfrank** [comment] 2023-07-11 22:02
You would need to find the plugin path for Homebridge (should be on the main page, bottom left). then go there and look for thehomebridge-wyze-smart-home plugin and go in there and find /src/accessories/WyzeAccessory.js. Open and edit this file, then save and restart homebridge.

**Comment by iamvidoq** [comment] 2023-07-11 22:38
Yeah i've looked there /Users/"myuser"/.homebridge but there isn't a plugin directory there.

<img width="236" alt="Screenshot 2023-07-11 at 6 38 00 PM" src="https://github.com/jfarmer08/homebridge-wyze-smart-home/assets/137729623/5cb61624-b518-4b1e-837d-cc997b6e4d0a">

**Comment by anderfrank** [comment] 2023-07-12 00:07
just search in Finder for the file name, I would think it would eventually find it.

**Comment by iamvidoq** [comment] 2023-07-12 14:23
That doesn't come up with anything. This is really strange!

**Comment by anderfrank** [comment] 2023-07-12 14:24
Maybe search from the root of your drive? Sorry I can't be of more help, I am running Homebridge in Docker.

**Comment by jfarmer08** [comment] 2023-07-12 19:03
You want to send me a copy of the cache Acc then I can take a look at what hardware you have and maybe identify the issue.

**Comment by jfarmer08** [comment] 2023-07-13 13:29
@iamvidoq cachedAccessories

**Comment by iamvidoq** [comment] 2023-07-13 13:34
@jfarmer08 

[cachedAccessories.zip](https://github.com/jfarmer08/homebridge-wyze-smart-home/files/12039899/cachedAccessories.zip)

**Comment by jfarmer08** [comment] 2023-07-13 13:53
Does the Pan 2 work like the Pan3 in respect to Onoff?

**Comment by anderfrank** [comment] 2023-07-13 13:54
As far as I understand the Pan v2 is exactly like the Pan v1 except it has the better night time camera sensor. I would expect it to function the same with the on/off feature the plugin provides.

**Comment by jfarmer08** [comment] 2023-07-13 16:21
I made an update that should help with this.

**Comment by iamvidoq** [comment] 2023-07-13 16:28
Oh wow thank you!

**Comment by iamvidoq** [comment] 2023-07-13 16:46
It seems to be working! No more errors.

**Comment by ptroche** [comment] 2023-07-13 18:55
Thank you so much! Now I can actually read my logs without them being spammed by this previous message.

**Comment by jfarmer08** [comment] 2023-07-13 21:35
@anderfrank For the new release for you, There is now a Enum.js file. I have added all the cameras, and comment out the ones that dont work currently. If we find more that do, then we can uncomment them.

**Comment by anderfrank** [comment] 2023-07-13 21:35
> @anderfrank For the new release for you, There is now a Enum.js file. I have added all the cameras, and comment out the ones that dont work currently. If we find more that do, then we can uncomment them.

Love it, thank you!

**Closed** 2023-07-14 14:46 UTC
Labels: question
